global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi_app:8000'] 
    metrics_path: /metrics 

  - job_name: 'crm_mock'
    static_configs:
      - targets: ['crm_mock:8001'] 
    metrics_path: /health # 僅檢查健康狀態
